### ISSUE TITLE
when pypi will be availabe

### ISSUE THREAD

**Issue by egy1st** [janjoswig/CNN#20]
I tried to install your repository according to your instructions but it triggers many many errors, when your pypi will be available

**Comment by janjoswig** [comment]
Thanks for your interest in the package! It will take me just a little longer to provide a stable enough build for PyPi.

Meanwhile, what are the errors you are getting? Which operating system are you on? This information could help me try to fix it.

I suspect it has to do with the build dependencies (in particular Cython). I updated those, so you could try to pull the latest changes and install again. Please note also, that the package has a few other Python dependencies (to be found in `requirements.txt` and/or `Pipfile`) and was only really tested so far under Python 3.8.

**Comment by janjoswig** [comment]
The package is now available on PyPi in its pre-release state.

**Comment by egy1st** [comment]
I received this error
https://prnt.sc/t9e1zf

**Comment by janjoswig** [comment]
@egy1st Thanks for the feedback. It looks like I needed to specify the NumPy headers to be included for the Cython extensions. I tested the install under Linux for Python 3.7 and Python 3.8. I hope this will work for you now.

**Comment by egy1st** [comment]
Many thanks. it works fine now.

Mohamed
